US132870  Accept Named Values
BrightspaceUILabs/multi-select pull request #118
Opened 2021-11-15 16:07 UTC by dkong-d2l

In order to avoid showing resource IDs to the user, we've modified the multi-select control to accept "named values," so that the data shown to the user is not necessarily the data sent by the control.  There is no "non-named" mode because, if you don't need this feature, you can simply have your names equal your values and it this control will work as it did before.

It's possible to have `assignableAttributes` elements that have the same value but having said elements with the same name will result in undefined behavior.  This was done to make the PR simpler, under the assumption that it's nonsensical for multiple items in the dropdown to have the same name (how would the user distinguish between the two?).

It still broadcasts just an array of the values and not their names, under the assumption that that's the only data clients of this control care about...

2021-11-16 16:15 UTC, BhamelinD2L requested changes
You should update the API docs in the readme and the attribute-picker's `static get properties()` to explain how to set available-Attributes correctly as its not a string array anymore. Aside from these small changes, I think we're all set! 

You should probably avoid merging this until you reconnect the API in foundation-components and have that side ready as well. Then we can deploy both repos at the same time and BSI will update cleanly with no downtime.

2021-11-16 16:15 UTC, BhamelinD2L commented on attribute-picker.js
> +						value: trimmedAttribute // this is unlikely to ever be right but what else can we do?!
If it isn't in the list then they're in allow-freeform. You'd expect they don't need ID within their particular use case if they're specifically opted in to let the user type anything, in which case it's correct to return what they're typing. In cases where `allowFreeform` is off like ours, this is a non-possibility. So I think things should be fine like this, we probably don't need the comment.

2021-11-16 18:33 UTC, dkong-d2l commented on attribute-picker.js
> +						value: trimmedAttribute // this is unlikely to ever be right but what else can we do?!
Oh yeah, I agree!  I meant to remove this comment before committing but I apparently forgot...

2021-11-16 19:11 UTC, BhamelinD2L commented on package.json
> +  "version": "5.0.0",
You don't need to do this - Prefix the merge commit or any other commit with `BREAKING CHANGE:` and you'll update the version as well as deploy. See the repo readme on deployment for more details

2021-11-16 20:41 UTC, dkong-d2l commented on package.json
> +  "version": "5.0.0",
Okay! ...but is there any harm in doing this?  Is it totally ineffectual?

2021-11-16 20:47 UTC, dkong-d2l commented on attribute-picker.js
> +	// TODO  Is there a reason why this function is async?
It turns out that this function was `async` because it had to `await` on `this.updateCompelte` before doing some post-processing.  I changed it to a `Promise.then()` clause, like all the other references to `this.updateComplete` in the file...

2021-11-17 14:40 UTC, dkong-d2l commented
Shouldn't I be able to simply merge this one first?  The version bump should prevent it from being included into any other repos until they're good and ready, no?

2021-11-17 16:43 UTC, BhamelinD2L commented on package.json
> +  "version": "5.0.0",
It might see the 5.0 and release it as 6.0 instead if you also did `BREAKING CHANGE:`, thus skipping 5.0 I actually don't know though! It could do nothing instead.

2021-11-17 16:45 UTC, BhamelinD2L commented
> Shouldn't I be able to simply merge this one first? The version bump should prevent it from being included into any other repos until they're good and ready, no?

https://github.com/Brightspace/brightspace-integration#making-a-bsi-release
BSI is always scanning for new changes and pulling them in. So if foundation components isn't merged at a similar time, it'll pull these changes in and be incompatible with foundation-components.

I think everyone else will be fine because you have only edited attribute-picker which nobody has adopted yet - but you'd break corpdev's COI page for a while.

2021-11-17 16:47 UTC, BhamelinD2L approved these changes

2021-11-26 16:54 UTC, BhamelinD2L commented
I've updated this to return the text/id object we had passed in instead of just the id, as it means we don't have to do a lookup on returned data. Much more convenient.

2021-11-29 16:30 UTC, merged